host.name=Fruzhin
host.version=0.3.0
# Genesis json data
genesis.path.polkadot=genesis/polkadot.json
genesis.path.kusama=genesis/ksmcc3.json
genesis.path.westend=genesis/westend2.json
#genesis.path.local=genesis/westend-local.json
genesis.path.local=genesis/zombienet/westend-local-single-auth.json
#genesis.path.local=genesis/zombienet/westend-local-multiple-auth.json

sync.state.path.polkadot=wss://polkadot.dotters.network
sync.state.path.kusama=wss://kusama.dotters.network
sync.state.path.westend=wss://westend.dotters.network

#logging.level.root=DEBUG
#logging.level.com.limechain.runtime.hostapi=DEBUG
#logging.level.com.limechain.consensus.beefy=DEBUG
#logging.level.com.limechain.network.protocol=ERROR