[relaychain]
chain = "westend-local"
default_command = "zombienet/inject-env-and-start.sh"
default_args = ["-n local --node-mode authoring --sync-mode full -dbc"]
chain_spec_path = "genesis/westend-raw.json"

[[relaychain.nodes]]
name = "alice"
validator = true
